server:
  port: 8083
camel:
  springboot:
    name: ServicesRest
    main-run-controller: true
management:
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
lt:
  liutikas:
    api:
      path: '/camel'
spring:
  main:
    web-application-type: none

person:
  api:
    url: http://localhost:8082/api/persons/
root:
  folder: file://dropbox/files