INSERT INTO  PERSON (OFFICIALID, NAME, LANGUAGEID) VALUES (1, 'Matas', 5);
INSERT INTO  PERSON (OFFICIALID, NAME, LANGUAGEID) VALUES (2, 'Martynas', 3);
INSERT INTO  PERSON (OFFICIALID, NAME, LANGUAGEID) VALUES (3, 'Marek', 1);
INSERT INTO  PERSON (OFFICIALID, NAME, LANGUAGEID) VALUES (4, 'Mantas', 1);
INSERT INTO  PERSON (OFFICIALID, NAME, LANGUAGEID) VALUES (5, 'Vytautas', 2);
INSERT INTO  PERSON (OFFICIALID, NAME, LANGUAGEID) VALUES (6, 'Laurynas', 4);